app/home/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, FileField, TextAreaField
from wtforms.validators import DataRequired, EqualTo, Email, Regexp, ValidationError
from app.models import User
from flask import session


class RegistForm(FlaskForm):
    """会员注册表单"""
    name = StringField(label="昵称",validators=[DataRequired("请输入昵称！")],
                       description="昵称",
                       render_kw={"class": "form-control input-lg","placeholder": "请输入昵称！","autofocus": ""
            # "required": "required"  # 添加强制属性，H5会在前端验证
        }
    )
    email = StringField(label="邮箱",validators=[DataRequired("请输入邮箱！"),Email("邮箱格式不正确！")],
                        description="邮箱",
                        render_kw={"class": "form-control input-lg","placeholder": "请输入邮箱！"})
    phone = StringField(label="手机",
                        validators=[DataRequired("请输入手机号码！"),
                                    Regexp("^1[3|4|5|7|8][0-9]{9}$", message="手机号码格式不正确！")],
                        description="手机",
                        render_kw={"class": "form-control input-lg","placeholder": "请输入手机号码！"})
    pwd = PasswordField(label="密码",
                        validators=[DataRequired("请输入密码！")],
                        description="密码",
                        render_kw={"class": "form-control input-lg","placeholder": "请输入密码！"}
    )
    re_pwd = PasswordField(label="确认密码",validators=[DataRequired("请再次输入密码！"),
            EqualTo('pwd', message="两次密码输入不一致！")],
                           description="确认密码",
                           render_kw={"class": "form-control input-lg","placeholder": "请再次输入密码！"})
    submit = SubmitField('注册',render_kw={"class": "btn btn-lg btn-success btn-block"})

    # 昵称验证
    def validate_name(self, field):
        name = field.data
        if User.query.filter_by(name=name).count() == 1:
            raise ValidationError("昵称已经存在！")

    def validate_email(self, field):
        email = field.data
        if User.query.filter_by(email=email).count() == 1:
            raise ValidationError("邮箱已经存在！")

    def validate_phone(self, field):
        phone = field.data
        if User.query.filter_by(phone=phone).count() == 1:
            raise ValidationError("手机号码已经存在！")

class LoginForm(FlaskForm):
    """会员登录表单"""
    name = StringField(label="账号",validators=[DataRequired("请输入账号！")],
                       description="账号",
                       render_kw={"class": "form-control input-lg","placeholder": "请输入账号！", "autofocus": ""})
    pwd = PasswordField(label="密码",validators=[DataRequired("请输入密码！")],
                        description="密码",render_kw={ "class": "form-control input-lg","placeholder": "请输入密码！"})
    submit = SubmitField('登录',render_kw={"class": "btn btn-lg btn-primary btn-block"})

    # 账号验证
    def validate_name(self, field):
        name = field.data
        if User.query.filter_by(name=name).count() == 0:
            raise ValidationError("账号不存在！")


class UserdetailForm(FlaskForm):
    """会员中心表单"""
    name = StringField(label="昵称",validators=[DataRequired("请输入昵称！")],
        description="昵称",render_kw={"class": "form-control","placeholder": "请输入昵称！"})
    email = StringField(label="邮箱",validators=[DataRequired("请输入邮箱！"),Email("邮箱格式不正确！") ],
                        description="邮箱",render_kw={"class": "form-control","placeholder": "请输入邮箱！"})
    phone = StringField(label="手机",validators=[DataRequired("请输入手机号码！"),Regexp("^1[3|4|5|7|8][0-9]{9}$", message="手机号码格式不正确！")],
                        description="手机",render_kw={"class": "form-control","placeholder": "请输入手机号码！"})
    face = FileField(label="头像",validators=[DataRequired("请上传头像！")],description="头像",
                     render_kw={"id": "input_face"})
    info = TextAreaField(label="简介",validators=[DataRequired("请输入简介！")],description="简介",
                         render_kw={"class": "form-control","rows": 10,"autofocus": ""})
    submit = SubmitField('保存修改',render_kw={"class": "btn btn-success"})

    def validate_name(self, field):
        if User.query.filter_by(name=field.data).count() == 1:
            if User.query.get(int(session["user_id"])).name != field.data:
                raise ValidationError("名称已经存在！")

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).count() == 1:
            if User.query.get(int(session["user_id"])).email != field.data:
                raise ValidationError("邮箱已经存在！")

    def validate_phone(self, field):
        if User.query.filter_by(phone=field.data).count() == 1:
            if User.query.get(int(session["user_id"])).phone != field.data:
                raise ValidationError("手机号码已经存在！")

class PwdForm(FlaskForm):
    """修改密码"""
    old_pwd = PasswordField(label="旧密码",validators=[DataRequired("请输入旧密码！")],
                            description="旧密码",
                            render_kw={"class": "form-control", "placeholder": "请输入旧密码！","autofocus": ""
        }
    )
    new_pwd = PasswordField(label="新密码",validators=[DataRequired("请输入新密码！")],
                            description="新密码",
                            render_kw={"class": "form-control","placeholder": "请输入新密码！"})
    submit = SubmitField('修改密码',
                         render_kw={"class": "btn btn-success"})

    # 旧密码验证
    def validate_old_pwd(self, field):
        old_pwd = field.data
        name = session["user"]
        user = User.query.filter_by(name=name).first()
        if not user.check_pwd(old_pwd):
            raise ValidationError("旧密码错误！")


class CommentForm(FlaskForm):
    content = TextAreaField(label='内容', validators=[DataRequired('请输入内容')], description='内容',
                            render_kw={"id": "input_content","autofocus": "" })
    submit = SubmitField('提交评论',render_kw={"class": "btn btn-success","id": "btn-sub" })

app/home/__init__.py
#coding:utf8

from .views import bp

app/home/views.py
#coding:utf8

from flask import Blueprint,render_template,redirect,url_for,flash,session,request,g,jsonify
from app.home.forms import RegistForm,LoginForm,UserdetailForm,PwdForm,CommentForm
from app.models import User,Userlog,Preview,Tag,Movie,Comment,Moviecol
from app.exts import db
import uuid
from functools import wraps
from app.admin.views import change_filename
from werkzeug.utils import secure_filename
import os
from app.config import DevConfig

bp=Blueprint('home',__name__)


@bp.before_request
def my_before_request():
    user_id=session.get('user_id')
    if user_id:
        user=User.query.filter(User.id==user_id).first()
        if user:
            g.user=user

@bp.context_processor
def my_context_processor():
    if hasattr(g, 'user'):
        return {'g_user': g.user}
    return {}

# 定义登录判断装饰器
def user_login_require(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        # session不存在时请求登录
        if "user" in session:
            return f(*args,**kwargs)
        return redirect(url_for("home.login", next=request.url))
    return decorated_function

@bp.route('/animation/')
def animation():
    data=Preview.query.all()
    return render_template('home/animation.html',data=data)

@bp.route('/')
def new_index():
    return redirect(url_for('home.index',page=1))

@bp.route('/<int:page>')
def index(page=None):
    tags = Tag.query.all()
    page_data = Movie.query
    # 通过url获取参数
    tid = request.args.get("tid", 0)

    if int(tid)!=0:
        page_data=page_data.filter_by(tag_id=int(tid))

    star = request.args.get("star",0)
    if int(star)!=0:
        page_data=page_data.filter_by(star=int(star))

    time = request.args.get("time",0)
    if int(time) != 0:
        if int(time) == 1:
            page_data=page_data.order_by(Movie.addtime.desc())
        else:
            page_data=page_data.order_by(Movie.addtime.asc())

    pm = request.args.get("pm",0)
    if int(pm) != 0:
        if int(pm) == 1:
            page_data=page_data.order_by(Movie.playnum.desc())
        else:
            page_data=page_data.order_by(Movie.playnum.asc())

    cm = request.args.get("cm",0)
    if int(cm) != 0:
        if int(time) == 1:
            page_data=page_data.order_by(Movie.commentnum.desc())
        else:
            page_data=page_data.order_by(Movie.commentnum.asc())


    # 保存获取的参数
    p = dict(
        tid=tid,
        star=star,
        time=time,
        pm=pm,
        cm=cm
    )



    # 分页处理
    if page is None:
        page=1

    page_data = page_data.paginate(page=page, per_page=DevConfig.PAGE_SET)

    return render_template("home/index.html", tags=tags, p=p, page_data=page_data)


@bp.route('/login/',methods=['POST','GET'])
def login():
    form=LoginForm()
    if form.validate_on_submit():
        name=form.name.data
        user=User.query.filter_by(name=name).first()

        if user and user.pwd == form.pwd.data:
            flash('登陆成功','ok')
            session['user']=user.name
            session['user_id']=user.id


            userlog=Userlog(user_id=user.id,ip=request.remote_addr)
            db.session.add(userlog)
            db.session.commit()

            return redirect(url_for('home.user'))
        else:
            flash('账号或密码错误','err')
    return render_template('home/login.html',form=form)


@bp.route('/logout/')
@user_login_require
def logout():
    session.pop('user', None)
    session.pop("user_id", None)
    return redirect(url_for('home.login'))


@bp.route('/register/',methods=['POST','GET'])
def register():
    form=RegistForm()
    if form.validate_on_submit():
        data=form.data
        user=User(
            name=data['name'],
            email=form.email.data,
            phone=form.phone.data,
            pwd=form.pwd.data,
            uuid= uuid.uuid4().hex
        )
        db.session.add(user)
        db.session.commit()
        flash('注册成功','ok')
        return redirect(url_for('home.login'))
    return render_template('home/register.html',form=form)


@bp.route('/user/',methods=['POST','GET'])
@user_login_require
def user():
    form = UserdetailForm()
    user = User.query.get(int(session["user_id"]))
    if user.face is not None:
        form.face.validators = []
    if request.method == "GET":
        form.name.data = user.name
        form.email.data = user.email
        form.phone.data = user.phone
        form.info.data = user.info
    if form.validate_on_submit():
        data = form.data

        if not os.path.exists(DevConfig.UP_DIR + "users" + os.sep):
            os.makedirs(DevConfig.UP_DIR + "users" + os.sep)
            os.chmod(DevConfig.UP_DIR + "users" + os.sep, "rw")

        if form.face.data.filename != '':
            old_face = user.face
            file_face = secure_filename(form.face.data.filename)
            user.face = change_filename(file_face)
            form.face.data.save(DevConfig.UP_DIR + "users" + os.sep + user.face)
            if old_face is not None and os.path.exists(DevConfig.UP_DIR + "users" + os.sep + old_face):
                os.remove(DevConfig.UP_DIR + "users" + os.sep + old_face)

        user.name = data["name"]
        user.email = data["email"]
        user.phone = data["phone"]
        user.info = data["info"]
        db.session.add(user)
        db.session.commit()
        flash("修改成功！", "ok")
    return render_template("home/user.html", form=form, user=user)


@bp.route('/pwd/',methods=['POST','GET'])
@user_login_require
def pwd():
    form = PwdForm()
    if form.validate_on_submit():
        data = form.data
        user = User.query.filter_by(name=session["user"]).first()
        user.pwd = data['new_pwd']
        db.session.add(user)
        db.session.commit()
        session.pop('user', None)
        session.pop("user_id", None)
        flash("修改密码成功，请重新登录！", "ok")
        return redirect(url_for("home.logout"))
    return render_template("home/pwd.html", form=form)


@bp.route('/comments/<int:page>')
@user_login_require
def comments(page=None):
    if page is None:
        page=1
    page_data = Comment.query.filter_by(user_id=g.user.id).\
        order_by(Comment.addtime.desc()).paginate(page=page,per_page=DevConfig.PAGE_SET)
    return render_template('home/comments.html',page_data=page_data)


@bp.route('/loginlog/<int:page>')
@user_login_require
def loginlog(page=None):
    if page is None:
        page=1
    page_data=Userlog.query.\
        filter_by(user_id=int(session['user_id'])).\
        order_by(Userlog.addtime.desc()).paginate(page=page,per_page=DevConfig.PAGE_SET)
    return render_template('home/loginlog.html',page_data=page_data)

@bp.route('/moviecol/add/')
@user_login_require
def moviecol_add():
    uid=request.args.get('uid','')
    mid=request.args.get('mid','')
    moviecol=Moviecol.query.filter_by(user_id=int(uid),movie_id=int(mid)).count()
    print(uid,mid,moviecol)
    if moviecol==1:
        data=dict(ok=0)

    elif moviecol==0:
        moviecol = Moviecol(user_id=int(uid),movie_id=int(mid))
        data=dict(ok=1)
        db.session.add(moviecol)
        db.session.commit()

    return jsonify(data)

@bp.route('/moviecol/<int:page>')
@user_login_require
def moviecol(page=None):
    if page is None:
        page=1
    page_data=Moviecol.query.filter_by(user_id=g.user.id).order_by(Moviecol.addtime.desc()).paginate(page=page,per_page=DevConfig.PAGE_SET)
    return render_template('home/moviecol.html',page_data=page_data)


@bp.route('/search/<int:page>')
def search(page):
    if page is None:
        page=1
    key=request.args.get('key','')
    key_count=Movie.query.filter(Movie.title.ilike('%' + key + '%')).count()
    page_data=Movie.query.filter(Movie.title.ilike('%'+key+'%')).\
        order_by(Movie.addtime.desc()).paginate(page=page,per_page=DevConfig.PAGE_SET)
    page_data.key=key
    return render_template('home/search.html',key=key,page_data=page_data,key_count=key_count)


@bp.route('/play/<int:id>/<int:page>',methods=['POST','GET'])
@user_login_require
def play(id=None,page=None):
    if page is None:
        page=1
    movie=Movie.query.get_or_404(int(id))
    form=CommentForm()

    if 'user' in session and form.validate_on_submit():
        comment=Comment(content=form.content.data,movie_id=movie.id,user_id=session['user_id'])
        db.session.add(comment)
        db.session.commit()
        movie.commentnum = movie.commentnum + 1
        db.session.add(movie)
        db.session.commit()

        flash('添加评论成功','ok')
        return redirect(url_for('home.play',id=movie.id,page=1))

    movie.playnum = movie.playnum + 1
    db.session.add(movie)
    db.session.commit()

    page_data = Comment.query.filter_by(movie_id=movie.id).order_by(Comment.addtime.desc()).paginate(page=page, per_page=5)
    return render_template('home/play.html',movie=movie,form=form,page_data=page_data)

app/templates/home/home.html
{% from 'home/macros.html' import static %}

<!doctype html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1 , user-scalable=no">
    <title>短视频</title>
    <link rel="shortcut icon" href="{{ url_for('static',filename='static/base/images/logo.png')}}"/>
    <link rel="stylesheet" href="{{ static('base/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ static('base/css/bootstrap-movie.css') }}" >
    <link rel="stylesheet" href="{{ static('base/css/animate.css') }}">
    <style>
        .navbar-brand>img {
            display: inline;
        }
        .media{
            padding:3px;
            border:1px solid #ccc
        }
    </style>
    {% block head %}{% endblock %}
</head>

<body>
<!--导航-->
<nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
        <!--小屏幕导航按钮和logo-->
        <div class="navbar-header">
            <button class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="{{ url_for('home.index',page=1) }}" class="navbar-brand" style="width:250px;">
                <img src="{{ static('base/images/logo.png') }}" style="height:30px;">&nbsp;短视频
            </a>
        </div>
        <!--小屏幕导航按钮和logo-->
        <!--导航-->
        <div class="navbar-collapse collapse">
            <form class="navbar-form navbar-left" role="search" style="margin-top:18px;" method="get" action="{{ url_for('home.search',page=1) }}">
                <div class="form-group input-group">
                    <input type="text" class="form-control" placeholder="请输入视频名！" id="key_movie" name="key" value="{{ key }}">
                    <span class="input-group-btn">
                        <a class="btn btn-default" id="do_search" ><span class="glyphicon glyphicon-search"></span>&nbsp;搜索</a>
                    </span>
                </div>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="curlink" href="{{ url_for('home.index',page=1) }}"><span class="glyphicon glyphicon-film"></span>&nbsp;视频</a>
                </li>
                {% if session['user'] %}
                <li>
                    <a class="curlink" ><span ></span>&nbsp;{{ session['user']  }}</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.logout') }}"><span class="glyphicon glyphicon-log-out"></span>&nbsp;退出</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.user') }}"><span class="glyphicon glyphicon-user"></span>&nbsp;会员中心</a>
                </li>
                {% else %}
                <li>
                    <a class="curlink" href="{{ url_for('home.login') }}"><span class="glyphicon glyphicon-log-in"></span>&nbsp;登录</a>
                </li>
                <li>
                    <a class="curlink" href="{{ url_for('home.register') }}"><span class="glyphicon glyphicon-plus"></span>&nbsp;注册</a>
                </li>
                {% endif %}

            </ul>
        </div>
        <!--导航-->

    </div>
</nav>
<!--导航-->
<!--内容-->

    {% block content %}
    {% endblock %}
</div>
<!--内容-->
<!--底部-->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p>
                    ©&nbsp;2018&nbsp;雨晨同学
                </p>
            </div>
        </div>
    </div>
</footer>
<!--底部-->
<script src="{{ url_for('static',filename='base/js/jquery.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('static',filename='base/js/jquery.singlePageNav.min.js') }}"></script>
<script src="{{ static('base/js/wow.min.js') }}"></script>
<script src="{{ static('lazyload/jquery.lazyload.min.js') }}"></script>
<script src="//cdn.bootcss.com/holder/2.9.4/holder.min.js"></script>
{% block js_for_play %}{% endblock %}
<script>
    $(function() {
        new WOW().init();
    })

</script>
<script>
    $(document).ready(function() {
        $("img.lazy").lazyload({
            effect: "fadeIn"
        });
        $('#do_search').click(function () {
            var key=$("#key_movie").val();
            location.href='{{ url_for('home.search',page=1) }}?key='+key
        });


    });






</script>
<!DOCTYPE html>
<html>
<head>
    <title>document-enter</title>
</head>
<body>


</body>
</html>
<script>
{% block js %}{% endblock %}

</script>

</body>
</html>

app/templates/home/index.html
{% extends 'home/home.html' %}
{% from 'ui/home_page.html' import page %}
{% block content %}
    <section id="hotmovie" style="margin-top:76px">
        <div class="container">
            <div class="row wow fadeInRight" data-wow-delay="0.6s">
                <div class="row">
                    <iframe class="wow fadeIn" width="100%" height="375px" frameborder=0 scrolling=no
                            src="{{ url_for('home.animation') }}"></iframe>
                </div>
            </div>
        </div>
    </section>
    <!--热门视频-->
    <!--视频列表-->
    <section id="movielist">
        <div class="container">
            <div class="row wow fadeIn" data-wow-delay="0.6s">
                <div class="col-md-12 table-responsive">
                    <table class="table text-left table-bordered" id="movietags">
                        <tr>
                            <td style="width:10%;">视频标签</td>
                            <td style="width:90%;">
                            <a href="{{ url_for('home.index',page=1) }}" class="label label-info">
                                    <span class="glyphicon glyphicon-tag"></span>&nbsp;取消筛选</a>
                                {% for v in tags %}
                                <a href="{{ url_for('home.index',page=1) }}?tid={{ v.id }}&star={{ p['star'] }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm={{ p['cm'] }}" class="label label-info">
                                    <span class="glyphicon glyphicon-tag"></span>&nbsp;{{ v.name }}</a>
                                {% endfor %}
                        </tr>
                        <tr>
                            <td>视频星级</td>
                            <td>
                                {% for v in range(1,6) %}
                                <a href="{{ url_for('home.index',page=1) }}?tid={{ p['tid'] }}&star={{ v }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm={{ p['cm'] }}" class="label label-warning">
                                    <span class="glyphicon glyphicon-star"></span>&nbsp;{{ v }}星</a>
                                {% endfor %}
                            </td>
                        </tr>
                        <tr>
                            <td>上映时间</td>
                            <td>
                                <a href="{{ url_for('home.index',page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time=1&pm={{ p['pm'] }}&cm={{ p['cm'] }}"  class="label label-default"><span
                                        class="glyphicon glyphicon-time"> &nbsp;最近</span></a>
                                &nbsp;
                                <a href="{{ url_for('home.index',page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time=2&pm={{ p['pm'] }}&cm={{ p['cm'] }}" class="label label-default"><span
                                        class="glyphicon glyphicon-time"> &nbsp;更早</span></a>
                            </td>
                        </tr>
                        <tr>
                            <td>播放数量</td>
                            <td>
                                <a href="{{ url_for('home.index',page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm=1&cm={{ p['cm'] }}"
                                        class="label label-success"><span class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</span>
                                </a>
                                &nbsp;
                                <a href="{{ url_for('home.index',page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm=2&cm={{ p['cm'] }}"
                                        class="label label-danger"><span class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</span>
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td>评论数量</td>
                            <td>
                                <a href="{{ url_for('home.index',page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm=1"
                                        class="label label-success"><span class="glyphicon glyphicon-arrow-down"></span>&nbsp;从高到底</span>
                                </a>
                                &nbsp;
                                <a href="{{ url_for('home.index',page=1) }}?tid={{ p['tid'] }}&star={{ p['star'] }}&time={{ p['time'] }}&pm={{ p['pm'] }}&cm=2"
                                        class="label label-danger"><span class="glyphicon glyphicon-arrow-up"></span>&nbsp;从低到高</span>
                                </a>
                            </td>
                        </tr>
                    </table>
                </div>
                {% for v in page_data.items %}
                    <div class="col-md-3">
                        <div class="movielist text-center">
                            <!--<img data-original="holder.js/262x166"
                                     class="img-responsive lazy center-block" alt="">-->
                            <a href="{{ url_for('home.play',id=v.id,page=1) }}">
                            <img  src="{{ url_for('static',filename='movie_files/'+v.logo) }}" class="img-responsive center-block" style="width: 262px;height: 262px" alt=""></a>
                            <div class="text-left" style="margin-left:auto;margin-right:auto;width:210px;">
                                <span style="color:#999;font-style: italic;">{{ v.title }}</span><br>
                                <div>
                                    {% for x in range(1,v.star+1) %}
                                    <span class="glyphicon glyphicon-star" style="color:#FFD119"></span>
                                   {% endfor %}
                                    {% for v in range(v.star,5) %}
                                        <span class="glyphicon glyphicon-star-empty" style="color:#FFD119"></span>
                                    {% endfor %}

                                </div>
                            </div>
                            <a href="{{ url_for('home.play',id=v.id,page=1) }}" class="btn btn-primary" target="_blank" role="button"><span
                                    class="glyphicon glyphicon-play"></span>&nbsp;播放</a>
                        </div>
                    </div>
                {% endfor %}

                <div class="col-md-12">
                    <nav aria-label="Page navigation">
                       {{  page(page_data,'home.index') }}
                    </nav>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

app/templates/home/macros.html
{% macro static(filename) -%}
    {{ url_for('static',filename=filename) }}
{%- endmacro %}

app/templates/home/menu.html
<div class="col-md-3">
        <div class="list-group">
            <a id='m-1' href="{{ url_for('home.user') }}" class="list-group-item">
                <span class="glyphicon glyphicon-user"></span>&nbsp;会员中心
            </a>
             <a id='m-2' href="{{ url_for('home.pwd') }}" class="list-group-item">
                <span class="glyphicon glyphicon-lock"></span>&nbsp;修改密码
            </a>
            <a id='m-3' href="{{ url_for('home.comments',page=1) }}" class="list-group-item">
                <span class="glyphicon glyphicon-comment"></span>&nbsp;评论记录
            </a>
            <a id='m-4' href="{{ url_for('home.loginlog',page=1) }}" class="list-group-item">
                <span class="glyphicon glyphicon-calendar"></span>&nbsp;登录日志
            </a>
            <a id='m-5' href="{{ url_for('home.moviecol',page=1) }}" class="list-group-item">
                <span class="glyphicon glyphicon-heart"></span>&nbsp;收藏视频
            </a>
        </div>
    </div>

app/templates/home/search.html
{% extends 'home/home.html' %}
{% from 'ui/s_page.html' import page %}
{% block content %}

    <div class="container" style="margin-top:76px">
        <div class="row">
            <div class="col-md-12">
                <ol class="breadcrumb" style="margin-top:6px;">
                    <li>与"{{ key }}"有关的视频，共{{ key_count }}部</li>
                </ol>
            </div>
            <div class="col-md-12">
                {% for v in page_data.items %}
                <div class="media">
                    <div class="media-left">
                        <a href={{ url_for('home.play',id=v.id,page=1) }}>
                            <img class="media-object" style="width:131px;height: 83px " src="{{ url_for('static',filename='movie_files/'+v.logo) }}" alt={{ v.title }}>
                        </a>
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">{{ v.title }}<a href="{{ url_for('home.play',id=v.id,page=1) }}" class="label label-primary pull-right"><span
                                class="glyphicon glyphicon-play"></span>播放影片</a></h4>
                       {{ v.info }}
                    </div>
                </div>
                {% endfor %}

            </div>
            <div class="col-md-12 text-center">
                {{ page(page_data,'home.search') }}
            </div>
        </div>
    </div>
{% endblock %}